function [ card_string, predictedClasses ] = classify_card( i, regions, props)
%CLASSIFY_CARD given an image file with its associated regions from
%regionprops and the property matrix generated by findSymbols, returns a
%string representing the number and suit of the card and the classifcations
%of each of the symbols in the image as a column vector.
%   There are two training models in our projects (one for red and one for
%   black). The function will first determine the color of the suit and
%   then will classify the suit based off of the training model.
%   Suit division is as follows:
%         Black and 1: Spade
%         Black and 2: Club
%         Red and 1: Heart
%         Red and 2: Diamond

%determine color
isRed = findRedBlack(i,regions, props);

%remove the numbers from the symbol property matrix. Numbers have much
%higher compactness values than symbols
sortedprops = sortrows(props,2);
[rows,~] = size(sortedprops);
symbolProps = sortedprops(1:rows-2,:);

%counts the remaining number of symbols which is the card value + 2
card_value = size(symbolProps,1) - 2;

predictedClasses = [];
suit = 'unset';


%Based off of the suit, classify all of the symbols in the image, the
%overall suit is the mode of the classification of all of the symbols
if isRed

    load('trained_models/symbols_red.mat');

    for k = 1:size(symbolProps)

        predictedClasses = [predictedClasses;classify(symbolProps(k,2:end),redNumClass, redMeans, redInvcors, 3, redAprioris)];

    end

    finalClass = mode(predictedClasses); % Will select class 1 in case of tie

    if finalClass == 1

        suit = 'HEARTS';

    else

        suit = 'DIAMONDS';

    end

else

    load('trained_models/symbols_black.mat');

    for k = 1:size(symbolProps)

        predictedClasses = [predictedClasses;classify(symbolProps(k,2:end),blackNumClass, blackMeans, blackInvcors, 3, blackAprioris)];

    end

    finalClass = mode(predictedClasses); % Will select class 1 in case of tie

    if finalClass == 1

        suit = 'SPADES';

    else

        suit = 'CLUBS';

    end

end

card_string = strcat(num2str(card_value),{' of '},suit);    

end

